### PR TITLE
Jenkinsfile is source code

### PR DESCRIPTION
**Pull request by peterlynch**
Jenkinsfile is intended to be checked into SCM. As such it should contain a license just like any other source file.

https://www.jenkins.io/doc/book/pipeline/jenkinsfile/

### CODE REVIEW

**Review by mathieucarbou — APPROVED** [review]

**Comment by hazendaz** [comment]
@mathieucarbou Few questions here.  Testing in at least windows, Jenkinsfile will just throw a warning because it has no file extension.  What style would it have?  I presume those must be both figured out with standard code and not seeing how here.

**Comment by peterlynch** [comment]
My bad. I meant to follow up with pr adding slash star style format for
jenkinsfile...

**Comment by mathieucarbou** [comment]
@peterlynch could you please send a PR asap to rollback the support for Jenkins files ? I will be able to release a fix and it will give time for proper support and testing. I think the issue comes from the fact that license style detection is done based on the extension and this file has no extension.
I think that the code returning the extension of a file perhaps could return the file name if no extension is set so that we can correctly determine header styles based on either extension or fixed file names.

Thanks for the report @hazendaz 👍

**Comment by peterlynch** [comment]
I can try to do this in the next few days

**Comment by mathieucarbou** [comment]
@hazendaz : meanwhile, you could easily fix that by adding the Jenkins files in your list of excluded files I think.
Here is the commit FYI: https://github.com/mathieucarbou/license-maven-plugin/commit/33c7cd593503192283c30288154b745bbd47807f

**Comment by hazendaz** [comment]
@mathieucarbou Yes, thanks.  I did exactly that.  Not a huge deal for now.  Will be nice to see ability to license such files as we have a number of them that don't fit nicely currently.  Appreciate it!

**Pull request merged**
