### PR TITLE
Add POM project org name and url properties

### PR DESCRIPTION
**Pull request by peterlynch**
https://maven.apache.org/pom.html#Organization

### CODE REVIEW

**Comment by mathieucarbou** [comment]
Hi @peterlynch,
Please ensure all tests pass before submitting a PR and I will merge with pleasure 👍 
Thank you!

**Review by mathieucarbou — CHANGES_REQUESTED** [review]
Unable to merge yet:
- unit test is/are missing
- some tests do not pass

**Comment by peterlynch** [comment]
@mathieucarbou 

> unit test is/are missing

I'd be happy to add tests. I could find no existing tests that exercise any of the other existing POM properties replacements specifically. Do you have a suggestion where the best place to add these would be?

> some tests do not pass

Both linux and windows builds failed with a seemingly unrelated error?

`[ERROR] Plugin org.apache.maven.plugins:maven-site-plugin:3.9.0 or one of its dependencies could not be resolved: Could not find artifact org.apache.maven.plugins:maven-site-plugin:jar:3.9.0 in google-maven-central (https://maven-central.storage-download.googleapis.com/repos/central/data/) -> [Help 1]`

Seems like a google maven central mirror out of date issue and not related to my changes. Me wonders why you are not using the official repository https://repo1.maven.org/maven2

**Comment by mathieucarbou** [comment]
- there are some tests using the `defaultProperties` (`test_update`), but this would be easy to write a test injecting the `MavenProjectStub` with an organization.
- I will check for the build error. Something is wrong with Travis maybe. We are not enforcing any Maven repo anywhere and the one that is used is perhaps a proxy.

**Comment by mathieucarbou** [comment]
build is fixed now

**Comment by peterlynch** [comment]
let me re-submit this

**Pull request closed without merging**
